FROM rocm/dev-ubuntu-22.04:5.6.1

ARG DEBIAN_FRONTEND=noninteractive

# Run this container as unprivileged to avoid later issues with permissions on host.
ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    python3.10 \
    python3.10-dev \
    python3-pip && \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 && \
    python -m pip install -U pip

RUN adduser user sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# For some reason AMDGPU requires it.
RUN usermod -g video user
RUN usermod -a -G render user

USER user
WORKDIR /home/user

ENV PATH="/home/user/.local/bin:${PATH}"

# We need ONNX here because the dummy input generator relies on the ONNX config in Optimum, which is unwanted and needs to be fixed.
# NOTE: change once torch 2.1 is released, use RC for now
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/test/rocm5.6/
RUN pip install --no-cache-dir accelerate install optimum omegaconf==2.3.0 hydra-core==1.3.2 hydra_colorlog==1.2.0 psutil pandas onnx

RUN git clone https://github.com/RadeonOpenCompute/pyrsmi.git && cd pyrsmi && pip install -e .

# TODO: remove this
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

RUN git clone https://github.com/huggingface/optimum-benchmark.git && \
    cd optimum-benchmark && git checkout --track origin/debug-rocm && \
    pip install --no-dependencies -e .

ARG COMMIT_SHA
ARG COMMIT_DATE_GMT
ENV COMMIT_SHA=${COMMIT_SHA}
ENV COMMIT_DATE_GMT=${COMMIT_DATE_GMT}
COPY --chown=$USER_ID:$GROUP_ID transformers /home/user/transformers

WORKDIR /home/user/transformers
RUN git checkout $COMMIT_SHA && pip install -e .

WORKDIR /home/user/transformers-regression
CMD ["bash", "run_benchmark.sh"]
