defaults:
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility
  - override benchmark: training

experiment_name: bert_2gpu_training_ddp

model: bert-base-uncased
task: text-classification
device: cuda

benchmark:
  use_ddp: true
  dataset_shapes:
    dataset_size: 2000
    sequence_length: 273

hydra:
  sweeper:
    params:
      +benchmark.training_arguments.per_device_train_batch_size: 16,32
      backend.torch_dtype: float16,float32
