defaults:
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility
  - override benchmark: training

experiment_name: bert_1gpu_training

model: bert-base-uncased
task: text-classification
device: cuda

benchmark:
  dataset_shapes:
    dataset_size: 1500
    sequence_length: 256

backend:
    use_ddp: false

hydra:
  sweeper:
    params:
      +benchmark.training_arguments.per_device_train_batch_size: 32
      backend.torch_dtype: float16,float32
