defaults:
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: pytorch_bert_inference

model: hf-internal-testing/tiny-random-bert
task: text-classification
device: cpu

benchmark:
  memory: true
  duration: 5

hydra:
  sweeper:
    params:
      benchmark.input_shapes.batch_size: 1,4
