defaults:
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: llama_1gpu_inference

model: meta-llama/Llama-2-7b-chat-hf
device: cuda

benchmark:
  memory: false
  duration: 15
  new_tokens: 200
  input_shapes:
    sequence_length: 200

hydra:
  sweeper:
    params:
      benchmark.input_shapes.batch_size: 1,16
      backend.torch_dtype: float16,float32
