defaults:
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: pytorch_gpt2_inference

model: hf-internal-testing/tiny-random-gpt2
task: text-generation
device: cpu
