name: Transformers regression test

on:
  workflow_dispatch:
  schedule:
    - cron: 00 14 * * * # at 2pm every day

jobs:
  run-regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check latest SHA
        run: |
          git clone --branch main --depth 15 https://github.com/fxmarty/dummy-repo.git
          cd dummy-repo && git rev-list HEAD > latest_sha.txt

          echo "vars.TRANSFORMERS_LATEST_SHA = ${{ vars.TRANSFORMERS_LATEST_SHA }}"
          # ignore the SHA that have already been tested
          sed -i '/${{ vars.TRANSFORMERS_LATEST_SHA }}/Q' latest_sha.txt

          while read sha; do
            echo "SHA: $sha"
            git checkout $sha
            curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/fxmarty/transformers-regression-test/actions/variables/TRANSFORMERS_LATEST_SHA \
            -d "{\"name\": \"TRANSFORMERS_LATEST_SHA\", \"value\": \"${sha}\"}"
          done <latest_sha.txt

          git checkout main
