name: Transformers regression test

on:
  workflow_dispatch:
  schedule:
    - cron: 00 14 * * * # at 2pm every day

jobs:
  run-regression:
    runs-on: dgx-cluster
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check latest SHA
        run: |
          pwd
          ls
          git clone --branch main --depth 15 https://github.com/huggingface/transformers.git
          cd transformers && git rev-list HEAD > latest_sha.txt

          echo "vars.TRANSFORMERS_LATEST_SHA = ${{ vars.TRANSFORMERS_LATEST_SHA }}"
          # ignore the SHA that have already been tested
          sed -i '/${{ vars.TRANSFORMERS_LATEST_SHA }}/Q' latest_sha.txt

          # Reverse the order, to iterate from oldest to newest.
          tac latest_sha.txt > ../latest_sha_reverse.txt
          cd ..

          echo "Running regression tests on commits:"
          cat latest_sha_reverse.txt

          while read SHA; do
            # sudo is just for the cluster, that complains otherwise
            sudo docker build -f Dockerfile --build-arg COMMIT_SHA=${SHA} -t transformers-regression .

            sudo docker run --rm -v $(pwd):/transformers-regression transformers-regression:latest
            echo "******************** RUNNING TEST FOR SHA: $SHA ********************"
            # git checkout $SHA
            curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/fxmarty/transformers-regression-test/actions/variables/TRANSFORMERS_LATEST_SHA \
            -d "{\"name\": \"TRANSFORMERS_LATEST_SHA\", \"value\": \"${SHA}\"}"
          done <latest_sha_reverse.txt

          # git checkout main
