name: Transformers regression test

on:
  workflow_dispatch:
  schedule:
    - cron: 00 14 * * * # at 2pm every day

jobs:
  run-regression:
    runs-on: dgx-cluster
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check latest SHA
        run: |
          pwd
          whoami
          which python
